---
- hosts: localhost
  connection: local
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | molecule_from_yaml }}"
  tasks:
    - name: Destroy instances
      molecule_vagrant:
        instance_name: "{{ item.name }}"
        platform_box: "{{ item.box }}"
        state: destroy
      with_items:
        "{{ molecule_yml.platforms }}"
