---
dependency:
  name: galaxy
driver:
  name: vagrant
  raw_config_args:
    - "ssh.insert_key = false"
    - "ssh.private_key_path = ['~/.ssh/id_rsa', '~/.vagrant.d/insecure_private_key']"
  provider:
    name: virtualbox
  instances:
    - name: openhabtest
lint:
  name: yamllint
platforms:
  - name: openhabtest
    groups:
      - vagrant
    box: ubuntu/xenial64
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      # - "vm.network 'forwarded_port', guest: 8080, host: 7799"
      - "vm.synced_folder '/data', \
         '/vagrant_data', disabled: false"
    interfaces:
      - auto_config: true
        ip: 192.168.1.24
        network_name: public_network
        bridge: eno1
        # type: static
    config_options:
      synced_folder: true
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--cpuexecutioncap', '50']"
      - "customize ['modifyvm', :id, '--usb', 'on']"
      - "customize ['usbfilter', 'add', '4', '--target', :id, '--name',\
         'VIES', '--vendorid', '0x10c4', '--productid', '0xea60']"
        #  - name: krzysr
        # groups:
        # - smarthome
provisioner:
  name: ansible
  log: true
  inventory-file: ../../../smarthome-ansible/inventory.yml
  inventory:
    links:
      group_vars: ../../../smarthome-ansible/group_vars
  env:
    BASE_ROLES_PATH: $HOME/smarthome-devops/smarthome-ansible/roles
    ANSIBLE_ROLES_PATH: $HOME/smarthome-devops/smarthome-ansible/roles
  extra_vars:
    ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  env:
    MOLECULE_INVENTORY_FILE: ../../../smarthome-ansible/inventory.yml
  lint:
    name: flake8
